// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hocpnognxvtaprphtjoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvY3Bub2dueHZ0YXBycGh0am9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MTQzNDAsImV4cCI6MjA1MTk5MDM0MH0.erivuRJo9cLr5xp2L7D4NKqDfuILQvtlXaP4xA4t_K0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);